[package]
name = "sneaky_oracle_secure"
version = "0.1.0"
edition = "2024"


[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
pinocchio = "0.9.0"
pinocchio-pubkey = "0.3.0"
[dev-dependencies]
litesvm = "0.9.1"
solana-sdk = "3.0.0"
